---
- name: Executa docker system prune
  hosts: XXXXX
  become: true
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: XXXXX.pem 

  tasks:
    - name: Executa docker prune
      shell: sudo docker system prune -fa
      register: retorno

    - debug:
       msg: "{{ retorno.stdout_lines }}"
...
