---
- name: Instala SSMAgent
  hosts: XXXXXXX
  become: true
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: XXXXXXX.pem 

  tasks:
    - name: Instala SSMAgent
      shell: sudo yum install -y https://s3.sa-east-1.amazonaws.com/amazon-ssm-sa-east-1/latest/linux_amd64/amazon-ssm-agent.rpm
      register: retorno

    - debug:
       msg: "{{ retorno.stdout_lines }}"
...
